"""added phone placement and setting

Revision ID: a003ff3ebf30
Revises: 0fe6d1c2f4da
Create Date: 2020-03-11 11:49:58.750446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a003ff3ebf30'
down_revision = '0fe6d1c2f4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('phone_placement', sa.Integer(), nullable=True))
    op.add_column('sensor_data', sa.Column('setting', sa.Integer(), nullable=True))
    op.add_column('sensor_data_test', sa.Column('phone_placement', sa.Integer(), nullable=True))
    op.add_column('sensor_data_test', sa.Column('setting', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_data_test', 'setting')
    op.drop_column('sensor_data_test', 'phone_placement')
    op.drop_column('sensor_data', 'setting')
    op.drop_column('sensor_data', 'phone_placement')
    # ### end Alembic commands ###
